### ISSUE TITLE
How to get depth and extrinsic parameter?

### ISSUE THREAD

**Issue by oym1994** [droid-dataset/droid_policy_learning#22]
Hi, thanks for your great job. I want to use this data to train a 3D policy where point-cloud and extrinsic parameter are needed but unfortunately I cant see this information in the raw data. So can you provide this information or tell how to get these？

Thanks for your attention and wait for your kind response!

**Comment by kpertsch** [comment]
Hi! 
Thanks for your interest! The extrinsics and depth information is currently not stored in the RLDS dataset unfortunately.
For both, you need to process our raw dataset, which we also uploaded. The extrinsic information is stored in each episode's metadata file. 
For depth, we don't store the actual depth data (since it's tricky to compress and would blow up storage usage by a lot), but instead our raw data contains *stereo* video, which you can convert into depth images of the desired resolution, eg using ZED's stereo-to-depth model.
We are also working on releasing depth generated by a new TRI depth model, but the ETA on that is not super clear...
