### ISSUE TITLE
Where is the pre-trained policy checkpoints?

### ISSUE THREAD

**Issue by johnnevins** [droid-dataset/droid_policy_learning#7]
Hi, 
Appreciate the work you've done on this project, in the paper, you mentioned that "We are releasing all resources ... This includes the full dataset ..., pre-trained policy checkpoints, ..."
Wonder where can I find the pre-trained policy checkpoints? Thanks

**Comment by kpertsch** [comment]
Sorry, this is incorrect -- we decided to not release the checkpoints since they are specific to the target domains that we collected the small demonstration datasets in, so they would likely not work in other domains.
Best would be to collect a small target domain dataset in your domain and then use the policy learning code in this repo to train your own checkpoint -- sorry for the confusion!
